#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@frps-arm[-1]
	add ucitrack frps-arm
	set ucitrack.@frps-arm[-1].init=frps-arm
	commit ucitrack
EOF

frps-arm=$(uci -q get frps-arm.@frps-arm[-1])

if [ -z "$frps-arm" ]; then
	uci -q add frps-arm frps-arm
fi

if [ "x$frps-arm" != "xmain" ]; then
	uci -q batch <<-EOF >/dev/null
		rename frps-arm.@frps-arm[-1]="main"
		set frps-arm.main.enabled="0"
		commit frps-arm
	EOF
fi

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
